#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3
is_public=$4

parent_dir=/var/www/fazen_multi_webapp
if [ $path = "/" ]
then
    final_path=$parent_dir
    name="root_webapp"
else
    final_path=$parent_dir$path
    name=$(echo $2 | cut -d '/' -f 2)
fi

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a fazen_multi_webapp
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

sudo yunohost app setting fazen_multi_webapp name -v $name
sudo yunohost app setting fazen_multi_webapp label -v fazen_multi_webapp

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
echo "Wrong user"
    exit 1
fi

# Créer le dossier parent des webapp pour l'utilisateur
if test ! -d $parent_dir
then	# Créer le dossier parent uniquement si il n'existe pas
    sudo mkdir $parent_dir

    # Set permissions
    sudo chmod 775 -R $parent_dir
    sudo chown -hR www-data:www-data $parent_dir
else
    echo "Création du dossier $parent_dir ignorée, le dossier existe déjà."
fi

# Change data in configurations
#sed -i "s@HOST@$domain@g" ../sources/index_ftp.html

# Copy files to the right place
sudo mkdir $final_path
sudo cp ../sources/index.html $final_path/

# Set permissions
sudo chmod 775 -R $final_path
sudo chown -hR $user:www-data $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$name.conf

# Make app public if necessary
sudo yunohost app setting fazen_multi_webapp is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting fazen_multi_webapp skipped_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
