#!/bin/bash

user=$(sudo yunohost app setting fazen_multi_webapp ftp_user)
path=$(sudo yunohost app setting fazen_multi_webapp path)
domain=$(sudo yunohost app setting fazen_multi_webapp domain)

parent_dir=/var/www/fazen_multi_webapp
name=$(echo $2 | cut -d '/' -f 2)
if [ $path = "/" ]
then
    final_path=$parent_dir
    name="root_webapp"
else
    final_path=$parent_dir$path
    name=$(echo $2 | cut -d '/' -f 2)
fi

# Suppression du dossier de la webapp
sudo rm -rf $final_path
# Suppression de la config nginx de la webapp
sudo rm -f /etc/nginx/conf.d/$domain.d/$name.conf

# Vérifie si le dossier parent est vide. Ce qui signifie que toutes les webapp ont été désinstallées. Ainsi que le client ftp net2ftp.
if test -z "$(ls $parent_dir | head -n1)"
then
    sudo rmdir $parent_dir
fi

sudo service nginx reload
sudo yunohost app ssowatconf
