#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting multi_webapp domain)
path=$(sudo yunohost app setting multi_webapp path)
user=$(sudo yunohost app setting multi_webapp ftp_user)
is_public=$(sudo yunohost app setting multi_webapp is_public)

parent_dir=/var/www/multi_webapp
name=$(echo $2 | cut -d '/' -f 2)
if [ $path = "/" ]
then
    final_path=$parent_dir
    name="root_webapp"
else
    final_path=$parent_dir$path
    name=$(echo $2 | cut -d '/' -f 2)
fi

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$name.conf

# Make app public if necessary
sudo yunohost app setting multi_webapp is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting multi_webapp skipped_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
